name: buildWindows
 
on:
  workflow_dispatch
    
jobs:
  build_and_test:
    name: "Build and test"
    strategy:
      matrix:
        os: [windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Install Ninja (windows)
      run: choco install ninja
      if: matrix.os == 'windows-latest'
 
    - name: Install aqt
      if: matrix.os == 'windows-latest'
      shell: bash
      run: |
        python -m pip install aqtinstall
        
    - name: List available Qt architectures
      if: matrix.os == 'windows-latest'
      shell: bash
      run: |
        python -m aqt list-qt windows desktop
    
    - name: Install Qt
      uses: jurplel/install-qt-action@v3
      with:
        version: '6.10.0'
      
    - uses: ilammy/msvc-dev-cmd@v1
    - uses: actions/checkout@v3
    
    - name: Build
      run: cmake -S . -B build -G "Ninja Multi-Config" && cmake --build build --config Release

    - name: Prepare deploy directory
      if: matrix.os == 'windows-latest'
      shell: pwsh
      run: |
        $deployDir = "deploy"
        New-Item -ItemType Directory -Force -Path $deployDir | Out-Null
        Copy-Item "build/Release/appballHunt.exe" $deployDir/
        Write-Host "Deploy directory prepared:"
        Get-ChildItem $deployDir

    - name: Deploy Qt (Windows)
      if: matrix.os == 'windows-latest'
      shell: pwsh
      run: |
        cd deploy
        Write-Host "Running windeployqt6..."
        windeployqt6.exe appballHunt.exe --qmldir ${{ github.workspace }} --release --compiler-runtime
        Write-Host "Deployment result:"
        Get-ChildItem

    - name: Test if executable works
      if: matrix.os == 'windows-latest'
      shell: pwsh
      run: |
        cd deploy
        Write-Host "=== Running appballHunt.exe ==="
        ./appballHunt.exe || Write-Host "App exited with code $LASTEXITCODE"

    - name: Verify logfile output
      if: matrix.os == 'windows-latest'
      shell: pwsh
      run: |
        cd deploy
        Write-Host "=== Checking startupLog.txt ==="
        if (Test-Path startupLog.txt) {
          Write-Host "startupLog.txt found"
          $content = Get-Content startupLog.txt
          if ($content -match "run qt eventLoop") {
            Write-Host "Log contains 'run qt eventLoop'"
          } else {
            Write-Host "Log file found but message missing"
            Write-Host "----- Log content -----"
            Get-Content startupLog.txt
            exit 1
          }
        } else {
          Write-Host "startupLog.txt not found!"
          Get-ChildItem
          exit 1
        }

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: qt-app-${{ matrix.os }}
        path: deploy/
