name: buildMacOS

on:
  workflow_dispatch

jobs:
  build_and_test_macos:
    name: "Build and test (macOS)"
    runs-on: macos-latest
    steps:
    - name: Install Ninja
      run: brew install ninja

    - name: Install Qt
      uses: jurplel/install-qt-action@v3
      with:
        version: '6.9.2'
        modules: 'qtshadertools qtquick3d qtcharts qtgraphs'
        host: 'mac'
        
    - uses: actions/checkout@v3

    - name: Build
      run: |
        cmake -S . -B build -G "Ninja Multi-Config"
        cmake --build build --config Release

    - name: Prepare deploy directory
      run: |
        mkdir -p deploy
        cp -R build/Release/appTestVbus.app deploy/
        echo "Deploy directory contents:"
        ls -R deploy

    - name: Deploy Qt (macOS)
      run: |
        cd deploy
        echo "Running macdeployqt6..."
        macdeployqt6 appTestVbus.app \
          -qmldir=${{ github.workspace }} \
          -always-overwrite \
          -verbose=2
        # remove quarantine flag to test on macrunner
        xattr -cr appTestVbus.app
        # remove debug symbols manually
        ## echo "Stripping symbols..."
        ## strip appTestVbus.app/Contents/MacOS/appTestVbus || true
        echo "Deployment finished:"
        du -sh appTestVbus.app

    - name: Test if executable works
      shell: bash
      run: |
        cd deploy
        echo "=== Running appTestVbus.app (timed) ==="
        ./appTestVbus.app/Contents/MacOS/appTestVbus depTest&
        pid=$!
        sleep 10
        echo "Killing app after 10 seconds..."
        kill $pid || true

    - name: Verify logfile output
      shell: bash
      run: |
        cd deploy
        echo "=== Checking startupLog.txt ==="
        if [ -f startupLog.txt ]; then
          echo "startupLog.txt found"
          if grep -q "run qt eventLoop" startupLog.txt; then
            echo "Log contains 'run qt eventLoop'"
          else
            echo "Log file found but message missing"
            echo "----- Log content -----"
            #cat startupLog.txt
            #exit 1
          fi
        else
          echo "startupLog.txt not found!"
          ls -la
          #exit 1
        fi

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: qt-app-macos
        path: deploy/
