name: CI
 
on: push
jobs:
  build_and_test:
    name: "Build and test"
    strategy:
      matrix:
        os: [windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Install Ninja (Windows)
      run: choco install ninja
      if: matrix.os == 'windows-latest'
    
    - name: Install Ninja (macOS)
      run: brew install ninja
      if: matrix.os == 'macos-latest'
 
    - name: Install Qt
      uses: jurplel/install-qt-action@v3
      with:
        version: '6.5.3'
        
    - uses: ilammy/msvc-dev-cmd@v1
      if: matrix.os == 'windows-latest'
      
    - uses: actions/checkout@v3
    
    - name: Build
      run: cmake -S . -B build -G "Ninja Multi-Config" && cmake --build build --config Release
      
    - name: Deploy Qt (Windows)
      if: matrix.os == 'windows-latest'
      run: |
        cd build/Release
        windeployqt.exe appballHunt.exe --qmldir ${{ github.workspace }} --compiler-runtime --release
    
    - name: Deploy Qt (macOS)
      if: matrix.os == 'macos-latest'
      run: |
        cd build/Release
        macdeployqt appballHunt.app -qmldir=${{ github.workspace }} -always-overwrite
        
    - name: Test if executable works (Windows)
      if: matrix.os == 'windows-latest'
      run: |
        cd build/Release
        dir
        # Versuche die App zu starten (sollte zumindest Fehler zeigen)
        # ./appballHunt.exe --help || echo "Exit code: $LASTEXITCODE"
    
    - name: Test if executable works (macOS)
      if: matrix.os == 'macos-latest'
      run: |
        cd build/Release
        ls -la
        # Optional: Test ob die .app-Bundle existiert
        test -d appballHunt.app && echo "App bundle created successfully"
 
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: qt-app-${{ matrix.os }}
        path: build/Release/